worker_processes 4;

events {
    use           epoll;
    worker_connections  8192;
}

http {
  server_tokens off;
  include       mime.types;
  charset       utf-8;

  log_format custom '$remote_addr - $remote_user [$time_local] '
    '"$request" $status $body_bytes_sent '
    '"$http_referer" "$http_user_agent" '
    '$upstream_response_time';

  access_log /logs/access.log custom;

  upstream aurbit {
    server deployment-aurbit-endpoint-1:5050;
    server deployment-aurbit-endpoint-2:5050;
    server deployment-aurbit-endpoint-3:5050;
    server deployment-aurbit-endpoint-4:5050;
  }

  server {
    listen 80;
    server_name _;

    location / {
        proxy_pass http://aurbit;
    }
  }
}