services:
  server:
    image: ghcr.io/bharath1910/aurbit:1.0.0
    container_name: aurbit-endpoint
    networks:
      - aurbit
    ports:
      - "5050:5050"
    env_file:
      - ../.env

  nginx:
    image: nginx
    networks:
      - aurbit
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - nginxlogs:/logs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  # Metrices
  fluentd:
    build: ./fluentd
    container_name: aurbit-fluentd
    networks:
      - aurbit
    ports:
      - "24231:24231"

    depends_on:
      - nginx

    volumes:
      - nginxlogs:/var/log/nginx/:ro
      - ./fluentd/fluent.conf:/etc/fluent/fluentd.conf

  prometheus:
    image: prom/prometheus
    networks:
      - aurbit
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus-data:/prometheus"

volumes:
  nginxlogs:
  prometheus-data:

networks:
  aurbit:
